load("@rules_java//java:defs.bzl", "java_binary")

java_binary(
    name = "runner",
    srcs = ["Runner.java"],
    main_class = "com.cadizm.runner.Runner",
    deps = ["//src/main/java/com/cadizm/graph"],
)
