load("@rules_java//java:defs.bzl", "java_binary")

package(default_visibility = ["//visibility:public"])

java_library(
    name = "algorithms",
    srcs = ["DepthFirstSearch.java"],
    deps = [
        "@maven//:javax_validation_validation_api_2_0_1_Final",
    ],
)
