load("@rules_java//java:defs.bzl", "java_binary")

package(default_visibility = ["//visibility:public"])

java_library(
    name = "algorithms",
    srcs = ["DepthFirstSearch.java"],
    deps = [
        "@maven//:com_google_guava_guava_32_1_3_jre",
    ],
)
