load("@rules_java//java:defs.bzl", "java_binary")

java_binary(
    name = "graph-runner",
    srcs = ["GraphRunner.java"],
    main_class = "com.cadizm.runners.GraphRunner",
    deps = ["//src/java/com/cadizm/graph"],
)
