load("@rules_python//python:defs.bzl", "py_binary")
load("@pypi_deps//:requirements.bzl", "requirement")

py_binary(
    name = "day01",
    srcs = ["day01.py"],
    data = ["//src/resources/aoc/2017:input"],
    deps = ["//src/python/cadizm/util:resources"],
)

py_binary(
    name = "day02",
    srcs = ["day02.py"],
    data = ["//src/resources/aoc/2017:input"],
    deps = ["//src/python/cadizm/util:resources"],
)

py_binary(
    name = "day03",
    srcs = ["day03.py"],
    data = ["//src/resources/aoc/2017:input"],
    deps = ["//src/python/cadizm/util:resources"],
)

py_binary(
    name = "day04",
    srcs = ["day04.py"],
    data = ["//src/resources/aoc/2017:input"],
    deps = ["//src/python/cadizm/util:resources"],
)

py_binary(
    name = "day05",
    srcs = ["day05.py"],
    data = ["//src/resources/aoc/2017:input"],
    deps = ["//src/python/cadizm/util:resources"],
)

py_binary(
    name = "day06",
    srcs = ["day06.py"],
    data = ["//src/resources/aoc/2017:input"],
    deps = ["//src/python/cadizm/util:resources"],
)

py_binary(
    name = "day07",
    srcs = ["day07.py"],
    data = ["//src/resources/aoc/2017:input"],
    deps = ["//src/python/cadizm/util:resources"],
)

py_binary(
    name = "day08",
    srcs = ["day08.py"],
    data = ["//src/resources/aoc/2017:input"],
    deps = ["//src/python/cadizm/util:resources"],
)

py_binary(
    name = "day09",
    srcs = ["day09.py"],
    data = ["//src/resources/aoc/2017:input"],
    deps = ["//src/python/cadizm/util:resources"],
)

py_binary(
    name = "day10",
    srcs = ["day10.py"],
    data = ["//src/resources/aoc/2017:input"],
    deps = ["//src/python/cadizm/util:resources"],
)

py_binary(
    name = "day11",
    srcs = ["day11.py"],
    data = ["//src/resources/aoc/2017:input"],
    deps = ["//src/python/cadizm/util:resources"],
)

py_binary(
    name = "day12",
    srcs = ["day12.py"],
    data = ["//src/resources/aoc/2017:input"],
    deps = ["//src/python/cadizm/util:resources"],
)

py_binary(
    name = "day13",
    srcs = ["day13.py"],
    data = ["//src/resources/aoc/2017:input"],
    deps = ["//src/python/cadizm/util:resources"],
)

py_binary(
    name = "day14",
    srcs = ["day14.py"],
    data = ["//src/resources/aoc/2017:input"],
    deps = ["//src/python/cadizm/util:resources"],
)
