load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "matrix",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//src/java/com/cadizm/string",
        "//third_party:google_guava",
    ],
)
