name: CI
run-name: ${{ github.workflow }} run ${{ github.run_attempt }} by ${{ github.actor }}
on: [push]
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"
      - name: Mount bazel cache
        uses: actions/cache@v3
        with:
          path: "~/.cache/bazel"
          key: bazel
      - name: Run unit tests
        run: |
          bazelisk test --test_output=errors //...
